USE `orm`;

CREATE TABLE IF NOT EXISTS `ADDRESS`
(
    `ID` BIGINT PRIMARY KEY,
    `COUNTRY` NVARCHAR(255) NOT NULL,
    `CITY` NVARCHAR(255) NOT NULL,
    `STREET` NVARCHAR(255) NOT NULL,
    `POST_CODE` NVARCHAR(15) NOT NULL
);

CREATE TABLE IF NOT EXISTS `PROJECT`
(
    `ID` BIGINT PRIMARY KEY,
    `TITLE` NVARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS `EMPLOYEE`
(
    `ID` BIGINT PRIMARY KEY,
    `FIRST_NAME` NVARCHAR(255) NOT NULL,
    `LAST_NAME` NVARCHAR(255) NOT NULL,
    `BIRTHDAY` DATE NOT NULL,
    `ADDRESS_ID` BIGINT NOT NULL,
    CONSTRAINT `EMPLOYEE_FKEY` FOREIGN KEY (`ADDRESS_ID`) REFERENCES `ADDRESS` (`ID`)
);

CREATE TABLE IF NOT EXISTS `EMPL_PROJ`
(
    `EMPLOYEE_ID` BIGINT NOT NULL,
    `PROJECT_ID` BIGINT NOT NULL,
    CONSTRAINT `EMPL_PROJ_EMPLOYEE_ID_FK` FOREIGN KEY (`EMPLOYEE_ID`)
        REFERENCES `EMPLOYEE` (`ID`),
    CONSTRAINT `EMPL_PROJ_PROJECT_ID_FK` FOREIGN KEY (`PROJECT_ID`)
        REFERENCES `PROJECT` (`ID`)
);